services:
  # Backend API
  - type: web
    name: educaweb-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: educaweb-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        value: AIzaSyDmw-k9kzEEYzRsNoIb_JyC3ZkbB5YgaD0
      - key: GEMINI_MODEL
        value: gemini-2.5-pro
      - key: FRONTEND_URL
        value: https://educaweb-frontend.onrender.com

  # Frontend
  - type: static
    name: educaweb-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://educaweb-backend.onrender.com

databases:
  - name: educaweb-db
    plan: free